// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xdecode_main.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XDecode_main_CfgInitialize(XDecode_main *InstancePtr, XDecode_main_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axi4lites_BaseAddress = ConfigPtr->Axi4lites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XDecode_main_Start(XDecode_main *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDecode_main_ReadReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_AP_CTRL) & 0x80;
    XDecode_main_WriteReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XDecode_main_IsDone(XDecode_main *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDecode_main_ReadReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XDecode_main_IsIdle(XDecode_main *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDecode_main_ReadReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XDecode_main_IsReady(XDecode_main *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDecode_main_ReadReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XDecode_main_EnableAutoRestart(XDecode_main *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDecode_main_WriteReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_AP_CTRL, 0x80);
}

void XDecode_main_DisableAutoRestart(XDecode_main *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDecode_main_WriteReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_AP_CTRL, 0);
}

void XDecode_main_SetNalu_startcodeprefix_len(XDecode_main *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDecode_main_WriteReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_NALU_STARTCODEPREFIX_LEN_DATA, Data);
}

u32 XDecode_main_GetNalu_startcodeprefix_len(XDecode_main *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDecode_main_ReadReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_NALU_STARTCODEPREFIX_LEN_DATA);
    return Data;
}

void XDecode_main_SetNalu_len(XDecode_main *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDecode_main_WriteReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_NALU_LEN_DATA, Data);
}

u32 XDecode_main_GetNalu_len(XDecode_main *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDecode_main_ReadReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_NALU_LEN_DATA);
    return Data;
}

void XDecode_main_SetNalu_nal_unit_type(XDecode_main *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDecode_main_WriteReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_NALU_NAL_UNIT_TYPE_DATA, Data);
}

u32 XDecode_main_GetNalu_nal_unit_type(XDecode_main *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDecode_main_ReadReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_NALU_NAL_UNIT_TYPE_DATA);
    return Data;
}

void XDecode_main_SetNalu_nal_reference_idc(XDecode_main *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDecode_main_WriteReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_NALU_NAL_REFERENCE_IDC_DATA, Data);
}

u32 XDecode_main_GetNalu_nal_reference_idc(XDecode_main *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDecode_main_ReadReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_NALU_NAL_REFERENCE_IDC_DATA);
    return Data;
}

void XDecode_main_SetNalu_forbidden_bit(XDecode_main *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDecode_main_WriteReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_NALU_FORBIDDEN_BIT_DATA, Data);
}

u32 XDecode_main_GetNalu_forbidden_bit(XDecode_main *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDecode_main_ReadReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_NALU_FORBIDDEN_BIT_DATA);
    return Data;
}

void XDecode_main_SetNalu_bit_offset(XDecode_main *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDecode_main_WriteReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_NALU_BIT_OFFSET_DATA, (u32)(Data));
    XDecode_main_WriteReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_NALU_BIT_OFFSET_DATA + 4, (u32)(Data >> 32));
}

u64 XDecode_main_GetNalu_bit_offset(XDecode_main *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDecode_main_ReadReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_NALU_BIT_OFFSET_DATA);
    Data += (u64)XDecode_main_ReadReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_NALU_BIT_OFFSET_DATA + 4) << 32;
    return Data;
}

void XDecode_main_SetNalu_bit_length(XDecode_main *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDecode_main_WriteReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_NALU_BIT_LENGTH_DATA, (u32)(Data));
    XDecode_main_WriteReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_NALU_BIT_LENGTH_DATA + 4, (u32)(Data >> 32));
}

u64 XDecode_main_GetNalu_bit_length(XDecode_main *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDecode_main_ReadReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_NALU_BIT_LENGTH_DATA);
    Data += (u64)XDecode_main_ReadReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_NALU_BIT_LENGTH_DATA + 4) << 32;
    return Data;
}

void XDecode_main_InterruptGlobalEnable(XDecode_main *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDecode_main_WriteReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_GIE, 1);
}

void XDecode_main_InterruptGlobalDisable(XDecode_main *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDecode_main_WriteReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_GIE, 0);
}

void XDecode_main_InterruptEnable(XDecode_main *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XDecode_main_ReadReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_IER);
    XDecode_main_WriteReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_IER, Register | Mask);
}

void XDecode_main_InterruptDisable(XDecode_main *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XDecode_main_ReadReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_IER);
    XDecode_main_WriteReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_IER, Register & (~Mask));
}

void XDecode_main_InterruptClear(XDecode_main *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDecode_main_WriteReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_ISR, Mask);
}

u32 XDecode_main_InterruptGetEnabled(XDecode_main *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDecode_main_ReadReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_IER);
}

u32 XDecode_main_InterruptGetStatus(XDecode_main *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDecode_main_ReadReg(InstancePtr->Axi4lites_BaseAddress, XDECODE_MAIN_AXI4LITES_ADDR_ISR);
}

